<?php
namespace QUDV\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-26 at 22:14:17.
 */
class NotSameTypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NotSameType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NotSameType;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
