<?php
namespace QUDV\Quantity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-26 at 20:56:10.
 */
class NZDTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NZD
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NZD;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers QUDV\Quantity\NZD::unit
     * @todo   Implement testUnit().
     */
    public function testUnit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers QUDV\Quantity\NZD::quantityKind
     * @todo   Implement testQuantityKind().
     */
    public function testQuantityKind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
