<?php
namespace QUDV\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-26 at 17:51:30.
 */
class NZDTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NZD
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NZD;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers QUDV\Unit\NZD::id
     * @todo   Implement testId().
     */
    public function testId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers QUDV\Unit\NZD::same
     * @todo   Implement testSame().
     */
    public function testSame()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers QUDV\Unit\NZD::name
     * @todo   Implement testName().
     */
    public function testName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers QUDV\Unit\NZD::symbol
     * @todo   Implement testSymbol().
     */
    public function testSymbol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers QUDV\Unit\NZD::description
     * @todo   Implement testDescription().
     */
    public function testDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
