<?php
namespace QUDV\Quantity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-26 at 21:23:38.
 */
class NZDTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NZD
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NZD(1.25);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers QUDV\Quantity\NZD::unit
     * @todo   Implement testUnit().
     */
    public function testUnit()
    {
        // Remove the following lines when you implement this test.
        $obj = $this->object->unit();
        if ($obj instanceof \QUDV\Unit\NZD) {
            $this->assertTrue(TRUE);
        } else {
            $this->assertTrue(FALSE);
        }
    }

    /**
     * @covers QUDV\Quantity\NZD::quantityKind
     * @todo   Implement testQuantityKind().
     */
    public function testQuantityKind()
    {
        $obj = $this->object->quantityKind();
        if($obj instanceof \QUDV\QuantityKind\Money) {
            $this->assertTrue(TRUE);
        } else {
            $this->assertTrue(FALSE);
        }
    }

    public function testAdd()
    {
        $obj = new NZD(1.25);
        $v = $this->object->add($obj);
        $this->assertEquals(2.5, $v->getValue());

    }
}
