<?php
namespace QUDV\Quantity\Converter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-28 at 14:41:16.
 */
class NZD2AUDTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NZD2AUD
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NZD2AUD(new \QUDV\Quantity\NZD(1));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers QUDV\Quantity\Converter\NZD2AUD::factor
     * @todo   Implement testFactor().
     */
    public function testFactor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers QUDV\Quantity\Converter\NZD2AUD::scale
     * @todo   Implement testScale().
     */
    public function testScale()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers QUDV\Quantity\Converter\NZD2AUD::convert
     * @todo   Implement testConvert().
     */
    public function testConvert()
    {
        $aud = $this->object->convert();
        $this->assertEquals(0.9, $aud->getValue());
    }
}
